#!/usr/bin/ruby

require 'fileutils'


logfile = "/Users/stephenfoster/Desktop/my_log"

File.open(logfile,"a") do |f|
	f.write("Started\n")
end

begin
	install_path = ARGV[0].split("/");
	install_path_prefix = install_path[0..(install_path.length-2)].join("/")
	file_name = install_path[install_path.length-1].split(".")[0]
	folder_name  = install_path_prefix + "/" + file_name;

	if File.exists?(folder_name)
		FileUtils.rm_r(folder_name)
	end

	Dir.mkdir(folder_name)

	FileUtils.mv(install_path.join("/"), folder_name)

	FileUtils.cp_r("./Assets/Vendor/June", folder_name)
	FileUtils.cp_r("./Assets/Vendor/June/MyJune", folder_name)

	File.open(logfile,"a") do |f|
		f.write("Okay\n")
	end

rescue Exception=>e
	File.open(logfile,"a") do |f|
		f.write("Problem: #{e}\n#{e.backtrace}\n")
	end
end
